# Generated by Django 3.0.4 on 2020-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(blank=True, max_length=10)),
                ('pc_name', models.CharField(max_length=15)),
                ('labo_name', models.CharField(max_length=15)),
                ('pc_number', models.IntegerField(max_length=5)),
            ],
        ),
    ]
