# Generated by Django 3.0.4 on 2020-03-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pc_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
