# Generated by Django 3.0.4 on 2020-03-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_auto_20200315_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=15)),
                ('labo_name', models.CharField(max_length=15)),
                ('pc_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='labo_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pc_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pc_number',
        ),
        migrations.RemoveField(
            model_name='report',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='report',
            name='report_description',
            field=models.TextField(default='No description for this report', max_length=2000),
        ),
        migrations.AddField(
            model_name='report',
            name='report_subject',
            field=models.CharField(default='Empty Subject', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='pc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Report.Pc'),
        ),
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Report.User'),
        ),
    ]
