# Generated by Django 3.0.4 on 2020-04-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_auto_20200328_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='vkey',
            field=models.IntegerField(default=426750),
        ),
    ]
