# Generated by Django 3.0.4 on 2020-06-09 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0005_report_vkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='stat',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='vkey',
            field=models.IntegerField(default=906750),
        ),
    ]
