# Generated by Django 3.0.4 on 2020-06-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0006_auto_20200609_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_subject',
            field=models.CharField(default='Empty Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='vkey',
            field=models.IntegerField(default=806250),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.Report')),
            ],
        ),
    ]
